apiVersion: tronador.stakater.com/v1alpha1
kind: EnvironmentProvisioner
metadata:
  generateName: stakater-nordmart-promotion-
spec:
  application:
    release:
      chart:
        git: https://github.com/stakater-lab/stakater-nordmart-promotion
        ref: add-tronador-yaml
        path: "deploy/"
      releaseName: add-tronador-yaml
      values:
        application:
          deployment:
            image:
              tag: "native"
