version: v1alpha1
targetBranches:
  - main
application:
  chartPath: "deploy/"
  chartVarsPath:
    - "values.yaml"
dependencies:
  repositories:
    - name: backend
      repository: github/stakater-lab 
      chartPath: deploy
      chartVarsRepoPath:
      - "values.yaml"
      valueOverrides:
      - "some.value=foobar"
  charts:
    - name: wordpress
      chartRepoPath: https://charts.bitnami.com/bitnami
      version: 12.0.3
      requires:
      - nginx
    - name: nginx
      chartRepoPath: https://charts.bitnami.com/bitnami
      version: 9.4.2
