application:
  applicationName: "promotion"
  configMap:
    enabled: true
    files:
    - nameSuffix: ""
      data:
        SQL_HOST: promotion-sql"
        SQL_USER:  root
  deployment:
    envFrom:
    - type: configmap
      name: ""
    additionalLabels:
      appCategory: "backend"
    annotations:
    resources: 
      limits:
         memory: 1Gi
         cpu: 0.5
      requests:
        memory: 128Mi
        cpu: 0.1
    imagePullSecrets: nexus-docker-config-forked
    image:
      repository: quay.io/tahonen/nordman-promotion
      tag: native
    volumes: {}
    envFrom:
    - type: configmap
      name: ""    
    env:
    - name: SQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: promotion-sql
          key:  mysql-root-password
    probes:
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 90
        httpGet:
          path: /
          port: 8080
      livenessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 90
        httpGet:
          path: /
          port: 8080
  service:
    ports:
    - port: 8080
      name: https
      targetPort: 8080
  rbac:
    create: true
    serviceAccount:
      enabled: true
      create: true
mysql:

  fullnameOverride: promotion-sql
  replication:
    enabled: false
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false

